### ISSUE TITLE
Angular +2 Example

### ISSUE THREAD

**Issue by akbast** [DerYeger/d3-graph-controller#29]
### Description

I have tried to setup an angular application with the [guide](https://graph-controller.yeger.eu/guide/). I am getting following error:

```
ERROR TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at ElementRef.children (selectChildren.js:6:1)
    at ElementRef.<anonymous> (selectAll.js:7:17)
    at Selection.__WEBPACK_DEFAULT_EXPORT__ [as selectAll] (selectAll.js:18:1)
    at Selection.__WEBPACK_DEFAULT_EXPORT__ [as selectChildren] (selectChildren.js:16:1)
    at GraphController.resetView (d3-graph-controller.es.js:797:11)
    at new GraphController (d3-graph-controller.es.js:612:1)
    at AppComponent.ngAfterViewInit (app.component.ts:94:25)
    at callHook (core.mjs:2542:1)
    at callHooks (core.mjs:2511:1)
```

Thanks for your help. 

### Reproduction

https://github.com/akbast/d3-graph-controller-angular

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Hi, thank you for the question!

Your typing are not correct.
The `ViewChild` `container` is not an `HTMLDivElement`, but an `ElementRef<HTMLDivElement>`.
`ElementRef` has to be imported from `@angular/core`.

Your property should be declared as follows.

```ts
@ViewChild('graph', { static: false }) container!: ElementRef<HTMLDivElement>;
```

You then have to pass the underlying native element to the controller as seen below.

```ts
this.controller = new GraphController(
      this.container.nativeElement,
      graph,
      config
);
```

I gave it a try in your reproduction repository and that should fix the issue.
Let me know if it works.

![image](https://user-images.githubusercontent.com/7950094/153893059-b4dc21dc-bc2d-4766-a0e8-5c5ea561bd74.png)

**Comment by DerYeger** [comment]
> Hey, thanks for the fast reply.
> 
> I can confirm that it works with suggested solution.
> 
> Thanks 😄

Awesome, thank you!
